name: Publish and Sign Container Images

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - "**/Dockerfile"
  schedule:
    - cron: "17 17 * * 0"

jobs:
  build-push-image:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: spotify-distrobox
            file: distroboxes/spotify/Dockerfile
          - image: steam-distrobox
            file: distroboxes/steam/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.4.1"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}
          tags: |
            latest
            type=sha,format=long
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Log into ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push container image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BWS_TOKEN }}
          base_url: https://vault.bitwarden.eu
          secrets: |
            3200b4c5-5543-4f22-83b2-b24000e08512 > COSIGN_PRIVATE_KEY
            c86c21ea-98cf-4ca9-b730-b2400146a3a5 > COSIGN_PASSWORD

      - name: Sign the container image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-push.outputs.digest }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}

      - name: Cleanup old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 30
